name: viral_detection
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pysam
  - samtools
  - bcftools
  - bowtie2
  - seqtk
  - star
  - parallel
  - gawk
  - git
  - vim
  - wget
